"""Tests for .tscn stripping from per-node pipeline output.

Per-node .tscn files generated by the LLM frequently contain mismatched
ExtResource IDs and incorrect script attachments (Bugs C, F). The wiring
stage owns all scene assembly, so per-node .tscn files are stripped.
"""

from backend.pipelines.contract.pipeline import _strip_node_tscn


def test_strip_tscn_removes_tscn_keys() -> None:
    node_files = {
        "player.gd": "code",
        "Player.tscn": "scene",
        "enemy.gd": "code2",
    }
    result = _strip_node_tscn(node_files)
    assert result == {"player.gd": "code", "enemy.gd": "code2"}


def test_strip_tscn_preserves_all_gd() -> None:
    node_files = {"a.gd": "x", "b.gd": "y"}
    result = _strip_node_tscn(node_files)
    assert result == {"a.gd": "x", "b.gd": "y"}


def test_strip_tscn_empty_dict() -> None:
    result = _strip_node_tscn({})
    assert result == {}


def test_strip_tscn_only_tscn() -> None:
    node_files = {"Scene.tscn": "data"}
    result = _strip_node_tscn(node_files)
    assert result == {}
